Feature: Allow User to control their VM (#124)
* Feature: VmClient

* Fix: Protocol (http/https) should not be hardcoded.

One place hardcoded `http://`, the other one `https://`.

* Fix: There was no test for `notify_allocation()`.

* WIP: Copy authentication functions from aleph-vm

* Fix: vm client sessions wasn't close + authentifications for test will use localhost as domain

* Add: Unit test for {perform_operation, stop, reboot, erase, expire}

* Refactor: logs didn't need to generate full header

Fix: extracts domain from node url instead of sending url

Fix: using vmclient sessions in get_logs instead of creating new one

* Add: get_logs test

* Fix: black in aleph_vm_authentification.py

fix: isort issue

Fix: mypy issue

Fix: black

Fix: isort

* Fix: fully remove _generate_header call in get_logs

Fix

Fix: using real path server instead of fake server for test

Fix: create playload

* Fix: black issue

* Fix: test fix workflow

* feat(vm_client): add missing types annotations

* refactor(vm_client): remove duplicated types annotations

* refactor(vm_client): avoid using single letter variable names

* feat(vm_client): increase test_notify_allocation precision

* refactor(vm_client): add empty lines for code readability

* style: run linting:fmt

* Fix: Required an old version of `aleph-message`

* Fix: Newer aleph-message requires InstanceEnvironment

Else tests were breaking.

* Fix: Qemu was not the default hypervisor for instances.

* Fix: Pythom 3.12 fails setup libsecp256k1

When "using bundled libsecp256k1", the setup using `/tmp/venv/bin/hatch run testing:test` fails to proceed on Python 3.12.

That library `secp256k1` has been unmaintained for more than 2 years now (0.14.0, Nov 6, 2021), and seems to not support Python 3.12.

The error in the logs:
```
File "/tmp/pip-build-env-ye8d6ort/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 862, in get_command_obj
 cmd_obj = self.command_obj[command] = klass(self)
                                                ^^^^^^^^^^^
      TypeError: 'NoneType' object is not callable
      [end of output]
```

See failing CI run:
https://github.com/aleph-im/aleph-sdk-python/actions/runs/9613634583/job/26516767722

* doc(README): command to launch tests was incorrect

* Refactor: create and sign playload goes to utils and some fix

* Fix: linting issue

* Fix: mypy issue

* fix: black

* feat: use bytes_from_hex where it makes sens

* chore: use ruff new CLI api

* feat: add unit tests for authentication mechanisms of VmClient

* fix: debug code remove

* Update vmclient.py

Co-authored-by: Olivier Le Thanh Duong <olivier@lethanh.be>

* Fix: update unit test to use stream_logs endpoint instead of logs

* Implement `VmConfidentialClient` class (#138)

* Problem: A user cannot initialize an already created confidential VM.

Solution: Implement `VmConfidentialClient` class to be able to initialize and interact with confidential VMs.

* Problem: Auth was not working

Corrections:
 *  Measurement type returned was missing field needed for validation of measurements
 * Port number was not handled correctly in authentifaction
 * Adapt to new auth protocol where domain is moved to the operation field (While keeping compat with the old format)
 * Get measurement was not working since signed with the wrong method
 * inject_secret was not sending a json
 * Websocked auth was sending a twice serialized json
 * update 'vendorized' aleph-vm auth file from source


Co-authored-by: Hugo Herter <git@hugoherter.com>
Co-authored-by: Laurent Peuch <cortex@worlddomination.be>
Co-authored-by: Olivier Le Thanh Duong <olivier@lethanh.be>
Co-authored-by: nesitor <amolinsdiaz@yahoo.es>